steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jiq25/jiq25-image:latest'
      - '.'
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/jiq25/jiq25-image:latest'